export const projects = [{
        id: 1,
        name: 'GCESports',
        info: 'A website that provide a platform to share information and memories of sports meet events.',
        img: './images/projects/gcesports.png',
        github: 'https://github.com/bibashmgr/gcesports',
        demo: 'https://www.error404s.tk/',
    },
    {
        id: 2,
        name: 'JaniHo',
        info: 'A website that provides the passengers to book tickets online for traveling around Nepal.',
        img: './images/projects/janiho.png',
        github: 'https://github.com/bibashmgr/JaniHo',
        demo: 'https://www.error404s.tk/',
    },
    {
        id: 3,
        name: 'Mero Projects',
        info: 'A website which contains mini-projects that are created while doing a self-study on reactjs.',
        img: './images/projects/mero-projects.png',
        github: 'https://github.com/bibashmgr/my-projects',
        demo: 'https://mero-projects.netlify.app/',
    },
];